url: https://ErasmusMC-Bioinformatics.github.io
baseurl: 

# Site settings
title: ErasmusMC Bioinformatics
email: a.stubbs@erasmusmc.nl
description: "Erasmus Medical Center Bioinformatcs Department"

# Team names, titles and social links
people:
- name: Andrew Stubbs
  pic: andrew
  position: Assistent Professor
  social:
    - title: mail
      url: a.stubbs@erasmsumc.nl
    - title: linkedin
      url: https://www.linkedin.com/in/andrew-stubbs-036b0026/
    - title: github
      url: https://github.com/Andrew-EMC

- name: Bas Horsman
  pic: bas
  position: Developer
  social:
    - title: github
      url: https://github.com/shorsman
    - title: linkedin
      url: https://www.linkedin.com/in/bas-horsman-7370492/

- name: David van Zessen
  pic: david
  position: Developer
  social:
    - title: github
      url: https://github.com/davidvanzessen

- name: Saskia Hiltemann
  pic: saskia
  position: PhD student
  social:
    - title: github
      url: https://github.com/shiltemann
    - title: linkedin
      url: https://www.linkedin.com/in/shiltemann/
    - title: twitter
      url: https://twitter.com/shiltemann

- name: Youri Hoogstrate
  pic: youri
  position: PhD student
  social:
    - title: github
      url: https://github.com/yhooogstrate

- name: Yunlei Li
  pic: yunlei
  position: Post-Doc
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #



# publications
publications:
- name: ega
  title: Integration of EGA secure data access into Galaxy
  journal: F1000 Research
  url: https://f1000research.com/articles/5-2841
  year: 2016
  month: December
  day: 16
  abstract: High-throughput molecular profiling techniques are routinely generating vast amounts of data for translational medicine studies. Secure access controlled systems are needed to manage, store, transfer and distribute these data due to its personally identifiable nature. The European Genome-phenome Archive (EGA) was created to facilitate access and management to long-term archival of bio-molecular data. Each data provider is responsible for ensuring a Data Access Committee is in place to grant access to data stored in the EGA. Moreover, the transfer of data during upload and download is encrypted. ELIXIR, a European research infrastructure for life-science data, initiated a project (2016 Human Data Implementation Study) to understand and document the ELIXIR requirements for secure management of controlled-access data.

- title: FuMa reporting overlap in RNA-seq detected fusion genes
  journal: Bioinformatics
  url: https://doi.org/10.1093/bioinformatics/btv721
  name: fuma
  abstract: blablabla

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/orgs/ErasmusMC-Bioinformatics
  - title: twitter
    url: https://twitter.com/ErasmusMC

# Postal address (add as many lines as necessary)
address:
  - line: Faculty Building
  - line: Room Ee15.79
  - line: Wytemaweg 80
  - line: 3015CN Rotterdam
  - line: The Netherlands

# Build settings
markdown: kramdown
permalink: pretty
