url: https://ErasmusMC-Bioinformatics.github.io
baseurl:

# Site settings
title: ErasmusMC Bioinformatics
email: a.stubbs@erasmusmc.nl
description: "Erasmus Medical Center Bioinformatcs Department"

# Team names, titles and social links
people:
- name: Andrew Stubbs
  pic: andrew.jpg
  position: Assistent Professor
  social:
    - title: mail
      url: a.stubbs@erasmsumc.nl
    - title: linkedin
      url: https://www.linkedin.com/in/andrew-stubbs-036b0026/
    - title: github
      url: https://github.com/Andrew-EMC

- name: Bas Horsman
  pic: bas.jpg
  position: Developer
  social:
    - title: github
      url: https://github.com/shorsman
    - title: linkedin
      url: https://www.linkedin.com/in/bas-horsman-7370492/

- name: David van Zessen
  pic: david.jpg
  position: Developer
  social:
    - title: github
      url: https://github.com/davidvanzessen

- name: Saskia Hiltemann
  pic: saskia.jpg
  position: PhD student
  social:
    - title: github
      url: https://github.com/shiltemann
    - title: linkedin
      url: https://www.linkedin.com/in/shiltemann/
    - title: twitter
      url: https://twitter.com/shiltemann

- name: Youri Hoogstrate
  pic: youri.jpg
  position: PhD student
  social:
    - title: github
      url: https://github.com/yhooogstrate

- name: Yunlei Li
  pic: yunlei.jpg
  position: Post-Doc
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #



# Publications
# these will be rendered on a timeline in the order encountered, please put in chronological order with newest first
publications:
- title: Integration of EGA secure data access into Galaxy
  journal: F1000 Research
  url: https://f1000research.com/articles/5-2841
  year: 2016
  month: December
  day: 16
  pic: ega.png
  abstract: High-throughput molecular profiling techniques are routinely generating vast amounts of data for translational medicine studies. Secure access controlled systems are needed to manage, store, transfer and distribute these data due to its personally identifiable nature. The European Genome-phenome Archive (EGA) was created to facilitate access and management to long-term archival of bio-molecular data. Each data provider is responsible for ensuring a Data Access Committee is in place to grant access to data stored in the EGA. Moreover, the transfer of data during upload and download is encrypted. ELIXIR, a European research infrastructure for life-science data, initiated a project (2016 Human Data Implementation Study) to understand and document the ELIXIR requirements for secure management of controlled-access data.

- title: FuMa reporting overlap in RNA-seq detected fusion genes
  journal: Bioinformatics
  url: https://doi.org/10.1093/bioinformatics/btv721
  year: 2015
  month: December
  day: 10
  pic: fuma.png
  abstract: A new generation of tools that identify fusion genes in RNA-seq data is limited in either sensitivity and or specificity. To allow further downstream analysis and to estimate performance, predicted fusion genes from different tools have to be compared. However, the transcriptomic con-text complicates genomic location-based matching. FusionMatcher (FuMa) is a program that reports identical fusion genes based on gene-name annotations.

- title: Discriminating somatic and germline mutations in tumor DNA samples without matching normals
  journal: Genome Research
  url: http://genome.cshlp.org/content/25/9/1382
  year: 2015
  month: July
  day: 24
  pic: virtualnormal.png
  abstract: Tumor analyses commonly employ a correction with a matched normal (MN), a sample from healthy tissue of the same individual, in order to distinguish germline mutations from somatic mutations. Since the majority of variants found in an individual are thought to be common within the population, we constructed a set of 931 samples from healthy, unrelated individuals, originating from two different sequencing platforms, to serve as a virtual normal (VN) in the absence of such an associated normal sample.

- title: ImmunoGlobulin galaxy (IGGalaxy) for simple determination and quantitation of immunoglobulin heavy chain rearrangements from NGS
  journal: BMC Immunology
  url: https://bmcimmunol.biomedcentral.com/articles/10.1186/s12865-014-0059-7
  year: 2014
  month: December
  day: 13
  pic: iggalaxy.jpg
  abstract: In this study we describe ImmunoGlobulin Galaxy (IGGalaxy)- a convenient web based application for analyzing next-generation sequencing results and reporting IGH gene rearrangements for both repertoire and clonality studies.

- title: A Department is born
  url: https://www.erasmusmc.nl/bioinformatica/
  abstract: In 2003, Erasmus MC took the first steps in order to establish a Center for Bioinformatics. Located in the heart of the biomedical research activities of Erasmus MC, this high-tech bioinformatics department is equipped with a state of the art hard- and software. In collaboration with other departments the center’s multidisciplinary team supports projects that generate genetics, genomics and proteomics data from basic research, forensics studies, molecular diagnostics and clinical trials. </br></br> The center also runs a research program of its own, which provides the biological and technological basis of all the other activities. The research focuses on the way the genome as a whole contributes to the evolution, development, structure and function of the brain. It involves analysis of gene expression in cells of the brain and combines genomics, proteomics and cytogenetic data to identify genes associated with neurological disorders or craniofacial and extremity malformations.


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/orgs/ErasmusMC-Bioinformatics
  - title: twitter
    url: https://twitter.com/ErasmusMC

# Postal address (add as many lines as necessary)
address:
  - line: Faculty Building
  - line: Room Ee15.79
  - line: Wytemaweg 80
  - line: 3015CN Rotterdam
  - line: The Netherlands

# Build settings
markdown: kramdown
permalink: pretty
