url: https://ErasmusMC-Bioinformatics.github.io
baseurl:

title: ErasmusMC Bioinformatics
email: a.stubbs@erasmusmc.nl
description: "Clincial Bioinformatics Erasmus Univeristy Medical Center"

welcome-message: Welcome To Our Lab!
welcome-subtitle: It's Nice To Meet You


# Collections (https://jekyllrb.com/docs/collections/ )
collections:
  services:
    order:  # TODO: order tag not working, but should?
      - galaxy.md
      - fair-data.md
      - training.md
      - clinical-diagnostics.md
      - ngs-methods.md
      - precision-medicine.md
  projects:
    output: true
    permalink: /:collection/:name
  publications:
    output: true
  people:
    order:
      - andrew.md
      - yunlei.md


# use icon names from fontawesome http://fontawesome.io/icons/
services-header:  Services
services-tagline: We aim to introduce innovative technologies from research into clinical practice.

projects-header: Projects
projects-tagline:

publications-header: Publications
publications-tagline:

about-header: About us
about-tagline:
about-image: erasmus_about.jpg
about-text:
    - paragraph: In 2003, Erasmus MC took the first steps in order to establish a Center for Bioinformatics. Located in the heart of the biomedical research activities of Erasmus MC, this high-tech bioinformatics department is equipped with a state of the art hard- and software. In collaboration with other departments the center’s multidisciplinary team supports projects that generate genetics, genomics and proteomics data from basic research, forensics studies, molecular diagnostics and clinical trials.
    - paragraph: The center also runs a research program of its own, which provides the biological and technological basis of all the other activities. The research focuses on the way the genome as a whole contributes to the evolution, development, structure and function of the brain. It involves analysis of gene expression in cells of the brain and combines genomics, proteomics and cytogenetic data to identify genes associated with neurological disorders or craniofacial and extremity malformations.

#################
#    TEAM
#################
team-header: Our Amazing Team
team-tagline:
team-footer:

#####################
#  COLLABORATIONS
#####################
collaborations:
- name: elixir
  logo: elixir.png

- name: dtl
  logo: dtl.jpg


####################
#  CONTACT
####################
contact-options:
- header: Visiting Address
  text:
    - line: Faculty Building
    - line: Room EE-1579
    - line: Wytemaweg 80
    - line: 3015CN Rotterdam
    - line: The Netherlands
  links:
    - description: Route and Parking
      url: https://www.erasmusmc.nl/en/contact-us

- header: Mailing Address
  text:
    - line: PO Box 2040
    - line: 3000 CA Rotterdam
    - line: The Netherlands

- header: E-mail us
  links:
    - description: bioinformatics@erasmusmc.nl
      url: mailto:bioinformatics@erasmusmc.nl
    - description: a.stubbs@erasmusmc.nl
      url: mailto:a.stubbs@erasmusmc.nl

- header: Call us
  text:
    - line: "Phone: +31 10 7043 491"
    - line: "Fax: +31 10 7044 161"


###############
#  FOOTER
###############
social:
  - title: github
    url: https://github.com/orgs/ErasmusMC-Bioinformatics
  - title: twitter
    url: https://twitter.com/ErasmusMC


### Build settings
markdown: kramdown
permalink: pretty

