title:              ErasmusMC Bioinformatics
email:              a.stubbs@erasmusmc.nl
description:        "Clincial Bioinformatics Erasmus Univeristy Medical Center"
author:             Willem de Koning
baseurl:
url:                https://ErasmusMC-Bioinformatics.github.io

# Social Profiles
twitter_username:   
github_username:    ErasmusMC-Bioinformatics
facebook_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code


# Collections (https://jekyllrb.com/docs/collections/ )
collections:
  applications:
    output: true
#    order:  # TODO: order tag not working, but should?
#      - galaxy.md
#      - fair-data.md
#      - training.md
#      - clinical-diagnostics.md
#      - ngs-methods.md
#      - precision-medicine.md
#  projects:
#    output: true
#    permalink: /:collection/:name
  publications:
    output: true
  team:
    order:
      - andrew.md
      - yunlei.md

#####################
#  COLLABORATIONS
#####################
collaborations:
- name: elixir
  logo: elixir.png

- name: dtl
  logo: dtl.jpg


####################
#  CONTACT
####################
contact-options:
- header: Visiting Address
  text:
    - line: Faculty Building
    - line: Room EE-1579
    - line: Wytemaweg 80
    - line: 3015CN Rotterdam
    - line: The Netherlands
  links:
    - description: Route and Parking
      url: https://www.erasmusmc.nl/en/contact-us

- header: Mailing Address
  text:
    - line: PO Box 2040
    - line: 3000 CA Rotterdam
    - line: The Netherlands

- header: E-mail us
  links:
    - description: bioinformatics@erasmusmc.nl
      url: mailto:bioinformatics@erasmusmc.nl
    - description: a.stubbs@erasmusmc.nl
      url: mailto:a.stubbs@erasmusmc.nl

- header: Call us
  text:
    - line: "Phone: +31 10 7043 491"
    - line: "Fax: +31 10 7044 161"


# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
