url: https://ErasmusMC-Bioinformatics.github.io
baseurl:

### Site settings
title: ErasmusMC Bioinformatics
email: a.stubbs@erasmusmc.nl
description: "Erasmus Medical Center Bioinformatcs Department"

welcome-message: Welcome To Our Lab!
welcome-subtitle: It's Nice To Meet You


### Services
# use logo names from fontawesome http://fontawesome.io/icons/
services-header: Services
services-tagline: We aim to introduce innovative technologies from research into clinical practice.

services:
- name: Galaxy
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.
  icon: star

- name: FAIR data
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.
  icon: laptop

- name: Training
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.
  icon: graduation-cap

- name: Databases
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.
  icon: database

- name: Molecular Medicine
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.
  icon: flask

- name: Clinical Diagnostics
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.
  icon: stethoscope

- name: Biobanking
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.
  icon: bank

### Projects


### Publications
publications-header: Publications
publications-tagline: Lorem ipsum dolor sit amet consectetur.

# these will be rendered on a timeline in the order encountered, please put in chronological order with newest first
publications:
- title: Integration of EGA secure data access into Galaxy
  journal: F1000 Research
  url: https://f1000research.com/articles/5-2841
  year: 2016
  month: December
  day: 16
  pic: ega.png
  abstract: High-throughput molecular profiling techniques are routinely generating vast amounts of data for translational medicine studies. Secure access controlled systems are needed to manage, store, transfer and distribute these data due to its personally identifiable nature. The European Genome-phenome Archive (EGA) was created to facilitate access and management to long-term archival of bio-molecular data.

- title: FuMa reporting overlap in RNA-seq detected fusion genes
  journal: Bioinformatics
  url: https://doi.org/10.1093/bioinformatics/btv721
  year: 2015
  month: December
  day: 10
  pic: fuma.png
  abstract: A new generation of tools that identify fusion genes in RNA-seq data is limited in either sensitivity and or specificity. To allow further downstream analysis and to estimate performance, predicted fusion genes from different tools have to be compared. However, the transcriptomic con-text complicates genomic location-based matching. FusionMatcher (FuMa) is a program that reports identical fusion genes based on gene-name annotations.

- title: Discriminating somatic and germline mutations in tumor DNA samples without matching normals
  journal: Genome Research
  url: http://genome.cshlp.org/content/25/9/1382
  year: 2015
  month: July
  day: 24
  pic: virtualnormal.png
  abstract: Tumor analyses commonly employ a correction with a matched normal (MN), a sample from healthy tissue of the same individual, in order to distinguish germline mutations from somatic mutations. Since the majority of variants found in an individual are thought to be common within the population, we constructed a set of 931 samples from healthy, unrelated individuals, originating from two different sequencing platforms, to serve as a virtual normal (VN) in the absence of such an associated normal sample.

- title: ImmunoGlobulin galaxy (IGGalaxy) for simple determination and quantitation of immunoglobulin heavy chain rearrangements from NGS
  journal: BMC Immunology
  url: https://bmcimmunol.biomedcentral.com/articles/10.1186/s12865-014-0059-7
  year: 2014
  month: December
  day: 13
  pic: iggalaxy.jpg
  abstract: In this study we describe ImmunoGlobulin Galaxy (IGGalaxy)- a convenient web based application for analyzing next-generation sequencing results and reporting IGH gene rearrangements for both repertoire and clonality studies.

- title: A Department is born
  year: 2003
  url: https://www.erasmusmc.nl/bioinformatica/
  pic: logo_bioinfemc.jpg
  abstract: In 2003, Erasmus MC took the first steps in order to establish a Center for Bioinformatics. Located in the heart of the biomedical research activities of Erasmus MC, this high-tech bioinformatics department is equipped with a state of the art hard- and software. In collaboration with other departments the center’s multidisciplinary team supports projects that generate genetics, genomics and proteomics data from basic research, forensics studies, molecular diagnostics and clinical trials. </br></br> The center also runs a research program of its own, which provides the biological and technological basis of all the other activities. The research focuses on the way the genome as a whole contributes to the evolution, development, structure and function of the brain. It involves analysis of gene expression in cells of the brain and combines genomics, proteomics and cytogenetic data to identify genes associated with neurological disorders or craniofacial and extremity malformations.



### Team
team-header: Our Amazing Team
team-tagline: Lorem ipsum dolor sit amet consectetur.
team-footer: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde.

# title should correspond with fontaswesome icon
people:
- name: Andrew Stubbs
  pic: andrew.jpg
  position: Assistent Professor
  contact:
    - icon: envelope
      url: mailto:a.stubbs@erasmsumc.nl
    - icon: linkedin
      url: https://www.linkedin.com/in/andrew-stubbs-036b0026/
    - icon: github
      url: https://github.com/Andrew-EMC

- name: Bas Horsman
  pic: bas.jpg
  position: Developer
  contact:
    - icon: envelope
      url: mailto:s.horsman@erasmsumc.nl
    - icon: github
      url: https://github.com/shorsman
    - icon: linkedin
      url: https://www.linkedin.com/in/bas-horsman-7370492/

- name: David van Zessen
  pic: david.jpg
  position: Developer
  contact:
    - icon: envelope
      url: mailto:d.vanzessen@erasmsumc.nl
    - icon: github
      url: https://github.com/davidvanzessen

- name: Saskia Hiltemann
  pic: saskia.jpg
  position: PhD student
  contact:
    - icon: envelope
      url: mailto:zazkia@gmail.com
    - icon: github
      url: https://github.com/shiltemann
    - icon: linkedin
      url: https://www.linkedin.com/in/shiltemann/
    - icon: twitter
      url: https://twitter.com/shiltemann

- name: Youri Hoogstrate
  pic: youri.jpg
  position: PhD student
  contact:
    - icon: envelope
      url: mailto:y.hoogstrate@erasmsumc.nl
    - icon: github
      url: https://github.com/yhooogstrate

- name: Yunlei Li
  pic: yunlei.jpg
  position: Post-Doc
  contact:
    - icon: envelope
      url: mailto:y.li1@erasmsumc.nl


### Collaborations

collaborations:
- name: elixir
  logo: elixir.png

- name: dtl
  logo: dtl.jpg

### Contact
contact-options:
- header: Visiting Address
  text:
    - line: Faculty Building
    - line: Room Ee15.79
    - line: Wytemaweg 80
    - line: 3015CN Rotterdam
    - line: The Netherlands
  links:
    - description: Route and Parking
      url: https://www.erasmusmc.nl/overerasmusmc/bereikbaarheid/erasmusmc_ziekenhuis/?lang=en

- header: Mailing Address
  text:
    - line: PO Box 2040
    - line: 3000 CA Rotterdam
    - line: The Netherlands

- header: E-mail us
  links:
    - description: bioinformatics@erasmusmc.nl
      url: mailto:bioinformatics@erasmusmc.nl
    - description: a.stubbs@erasmusmc.nl
      url: mailto:a.stubbs@erasmusmc.nl

- header: Call us
  text:
    - line: "Phone: +31 10 7043 491"
    - line: "Fax: +31 10 7044 161"

### Footer
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/orgs/ErasmusMC-Bioinformatics
  - title: twitter
    url: https://twitter.com/ErasmusMC

# Postal address (add as many lines as necessary)




### Build settings
markdown: kramdown
permalink: pretty
